### ISSUE TITLE
When I run the code, I get the following error

### ISSUE THREAD

**Issue by meleantonio** [economicanalysiswithmatrices/-OH#2]
Hi @economicanalysiswithmatrices/oh when I run your code on my MacBook Pro, I get the following error message:
```matlab
Error using imageDatastore (line 85)
Cannot find files or folders matching: '/Users/antoniomac/Dropbox/github/-OH/OH\Images\'.

Error in RingOfFireGame>RingOfFireGame_OpeningFcn (line 69)
imgs                = imageDatastore(imagesPath); %read path for all images

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in RingOfFireGame (line 42)
    gui_mainfcn(gui_State, varargin{:});
```
I think this is due to the fact that the Mac uses a different notation for paths on the computer, in particular, uses / instead of \ like Windows. I am sure that if you change the \ into /, it would work on Windows machines too.

**Comment by sk01104** [comment]
I have upload a Mac version zip file

**Comment by meleantonio** [comment]
@sk01104 awesome

![niceworkbro](https://user-images.githubusercontent.com/8898165/51030372-282d2800-1591-11e9-8416-55b6d70dbd5c.gif)
